### PR TITLE
Adding collation fixer procedure

### PR DESCRIPTION
**Pull request by Ara4Sh**
collation fixer is a simple procedure to convert all tables collation to new one in a database . 
for example : 
` CALL ps_helper.collation_fixer(dbname, utf8_persian_ci)`

### CODE REVIEW

**Comment by MarkLeith** [comment]
Hey, thanks for the submission. Would you like to instead submit this against https://github.com/mysql/mysql-sys ? This branch became the sys schema in MySQL itself (now in 5.7 by default), so if you submit this upstream there (and sign the OCA - http://www.oracle.com/technetwork/community/oca-486395.html), I can help get something like this in to the mainstream server as well..

Cheers,

Mark

**Comment by Ara4Sh** [comment]
Thank you , I will send the OCA and push the code to mysql-sys repo .

**Comment by Ara4Sh** [comment]
I changed the code and create a pull request https://github.com/mysql/mysql-sys/pull/110 and signed the oca thank you for guiding me

**Comment by MarkLeith** [comment]
Thanks! I'll close this one now then.

**Pull request closed without merging**
